// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenMultiFile(arg1, arg2, arg3) {
  return window['go']['core']['FilePicker']['OpenMultiFile'](arg1, arg2, arg3);
}

export function OpenSingleFile(arg1, arg2, arg3) {
  return window['go']['core']['FilePicker']['OpenSingleFile'](arg1, arg2, arg3);
}
