// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileDrop():Promise<void>;

export function FileDropOff():Promise<void>;

export function OpenMultiFile(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function OpenSingleFile(arg1:string,arg2:string,arg3:string):Promise<string>;
