package core

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"os/exec"
	"packify/config"
	"path/filepath"
	"strings"
)

type InstallationFileInfo struct {
	appConfig           *config.AppConfig
	FileName            string
	Version             string
	Arch                string
	IconPath            string
	BinaryPath          string
	OutputDir           string
	DesktopName         string
	MaintainerFirstName string
	MaintainerLastName  string
	MaintainerEmail     string
	Docs                []string
}

func NewInstallationFileInfo(appConfig *config.AppConfig) *InstallationFileInfo {
	return &InstallationFileInfo{appConfig: appConfig}
}

func createDebStructure(ifi *InstallationFileInfo, root string) {
	deb := filepath.Join(root, "DEBIAN")
	bin := filepath.Join(root, "usr", "local", "bin")
	icon := filepath.Join(root, "usr", "share", "icons", "hicolor", "256x256", "apps")
	desktop := filepath.Join(root, "usr", "share", "applications")
	doc := filepath.Join(root, "usr", "share", ifi.FileName)
	os.MkdirAll(deb, 0755)
	os.MkdirAll(bin, 0755)
	os.MkdirAll(icon, 0755)
	os.MkdirAll(desktop, 0755)
	os.MkdirAll(doc, 0755)

	// control
	control := fmt.Sprintf(
		`
		Package: %s
		Version: %s
		Section: utils
		Priority: optional
		Architecture: %s
		Maintainer: %s %s - %s
		Description: Generated by packify
		`,
		ifi.FileName, ifi.Version, ifi.Arch, ifi.MaintainerFirstName, ifi.MaintainerLastName, ifi.MaintainerEmail,
	)
	os.WriteFile(filepath.Join(deb, "control"), []byte(control), 0644)

	copyFile(ifi.BinaryPath, filepath.Join(bin, ifi.FileName))
	copyFile(ifi.IconPath, filepath.Join(icon, ifi.FileName+".png"))

	desktopEntry := fmt.Sprintf(
		`
		[Desktop Entry]
		Version=1.0
		Name=%s
		Exec=/usr/local/bin/%s
		Icon=%s
		Type=Application
		Categories=Utility;
		`,
		ifi.FileName, ifi.FileName, ifi.FileName,
	)
	os.WriteFile(filepath.Join(desktop, ifi.DesktopName), []byte(desktopEntry), 0644)

	for _, doc := range ifi.Docs {
		copyFile(doc, filepath.Join(root, "usr", "share", ifi.FileName, filepath.Base(doc)))
	}
}

func buildDeb(ifi *InstallationFileInfo, root string) string {
	debFile := fmt.Sprintf("%s_%s_%s.deb", ifi.FileName, ifi.Version, ifi.Arch)
	debPath := filepath.Join(filepath.Dir(root), debFile)
	exec.Command("dpkg-deb", "--build", root, debPath).Run()
	return debPath
}

func buildTarGz(ifi *InstallationFileInfo, root string) string {
	tarPath := filepath.Join(filepath.Dir(root), fmt.Sprintf("%s_%s_%s.tar.gz", ifi.FileName, ifi.Version, ifi.Arch))
	f, _ := os.Create(tarPath)
	defer f.Close()

	gz := gzip.NewWriter(f)
	defer gz.Close()

	tarWriter := tar.NewWriter(gz)
	defer tarWriter.Close()

	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}

		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = rel

		if err := tarWriter.WriteHeader(hdr); err != nil {
			return err
		}

		fp, err := os.Open(path)
		if err != nil {
			return err
		}
		defer fp.Close()

		_, err = io.Copy(tarWriter, fp)
		return err
	})

	return tarPath
}

func buildAppImage(ifi *InstallationFileInfo, root string) string {
	appDir := filepath.Join(filepath.Dir(root), ifi.FileName+".AppDir")
	os.MkdirAll(appDir, 0755)

	exec.Command("cp", "-r", filepath.Join(root, "usr"), appDir).Run()
	appRun := filepath.Join(appDir, "AppRun")
	os.WriteFile(appRun, []byte("#!/bin/sh\nexec /usr/local/bin/"+ifi.FileName), 0755)

	exec.Command("chmod", "+x", appRun).Run()
	appImage := strings.TrimSuffix(appDir, ".AppDir") + ".AppImage"
	exec.Command("appimagetool", appDir, appImage).Run()
	return appImage
}

func copyFile(src, dst string) {
	s, _ := os.Open(src)
	d, _ := os.Create(dst)
	defer s.Close()
	defer d.Close()
	io.Copy(d, s)
}

func (ifi *InstallationFileInfo) setInfo(data map[string]string) {
	// app => myapp, Application name
	// ver => 1.0.0, Version
	// arch => amd64, Architecture (amd64, arm64, i386)
	// icon => icon.png, Icon file
	// bin => ./myapp, Compiled binary path
	// out => ./dist, Output directory
	// docs => README.md,LICENSE, Comma-separated list of docs

	ifi.FileName = data["fileName"]
	ifi.Version = data["version"]
	ifi.Arch = data["arch"]
	ifi.IconPath = data["iconPath"]
	ifi.BinaryPath = data["binaryPath"]
	ifi.OutputDir = data["outputPath"]
	ifi.DesktopName = data["desktopName"] + ".desktop"
	ifi.Docs = strings.Split(data["docs"], ",")
}

func (ifi *InstallationFileInfo) StartProcess(data map[string]string) {
	ifi.setInfo(data)
	tempDir, _ := os.MkdirTemp("", "debgen")
	defer os.RemoveAll(tempDir)

	fmt.Println("[+] Creating structure...")
	debRoot := filepath.Join(tempDir, ifi.FileName+"-deb")
	createDebStructure(ifi, debRoot)

	fmt.Println("[+] Building .deb...")
	debPath := buildDeb(ifi, debRoot)

	fmt.Println("[+] Building .tar.gz...")
	tarPath := buildTarGz(ifi, debRoot)

	fmt.Println("[+] Building AppImage...")
	appImagePath := buildAppImage(ifi, debRoot)

	os.MkdirAll(ifi.OutputDir, 0755)
	copyFile(debPath, filepath.Join(ifi.OutputDir, filepath.Base(debPath)))
	copyFile(tarPath, filepath.Join(ifi.OutputDir, filepath.Base(tarPath)))
	copyFile(appImagePath, filepath.Join(ifi.OutputDir, filepath.Base(appImagePath)))

	fmt.Println("✅ Done. Packages saved to:", ifi.OutputDir)
}
