package core

import (
	"archive/tar"
	"compress/gzip"
	"fmt"
	"io"
	"os"
	"os/exec"
	"packify/assets"
	"packify/config"
	"path/filepath"
	"runtime"
)

type InstallationFileInfo struct {
	appConfig           *config.AppConfig
	FileName            string
	Version             string
	Arch                string
	IconPath            string
	BinaryPath          string
	OutputFormat        string
	OutputPath          string
	DesktopName         string
	MaintainerFirstName string
	MaintainerLastName  string
	MaintainerEmail     string
	Docs                []string
}

func NewInstallationFileInfo(appConfig *config.AppConfig) *InstallationFileInfo {
	return &InstallationFileInfo{appConfig: appConfig}
}

func getArch(key string) string {
	var archMap = map[string]string{
		"amd64":   "x86_64",
		"386":     "i686",
		"arm":     "armhf",
		"arm64":   "aarch64",
		"ppc64":   "ppc64",
		"ppc64le": "ppc64le",
		"riscv64": "riscv64",
		"s390x":   "s390x",
	}

	result, ok := archMap[key]
	if !ok {
		return "x86_64"
	}

	return result
}

func createDesktopIcon(ifi *InstallationFileInfo, dir string, executeFromRoot bool) {
	exceDir := "usr/local/bin/"
	if executeFromRoot {
		exceDir = "/" + exceDir
	}
	entry := fmt.Sprintf("[Desktop Entry]\nVersion=%s\nName=%s\nExec=%s%s\nIcon=%s\nType=Application\nCategories=Utility;",
		ifi.Version, ifi.DesktopName, exceDir, ifi.FileName, ifi.FileName,
	)
	os.WriteFile(filepath.Join(dir, ifi.FileName+".desktop"), []byte(entry), 0644)
}

func createUsrDirs(ifi *InstallationFileInfo, root string) map[string]string {
	paths := make(map[string]string)

	paths["bin"] = filepath.Join(root, "usr", "local", "bin")
	paths["icon"] = filepath.Join(root, "usr", "share", "icons", "hicolor", "256x256", "apps")
	paths["desktop"] = filepath.Join(root, "usr", "share", "applications")
	paths["docs"] = filepath.Join(root, "usr", "share", "doc", ifi.FileName)

	os.MkdirAll(paths["bin"], 0755)
	os.MkdirAll(paths["icon"], 0755)
	os.MkdirAll(paths["desktop"], 0755)
	os.MkdirAll(paths["docs"], 0755)

	return paths
}

func createDebStructure(ifi *InstallationFileInfo, root string) {
	fmt.Println("[+] Creating deb structure...")
	deb := filepath.Join(root, "DEBIAN")
	os.MkdirAll(deb, 0755)
	usrPaths := createUsrDirs(ifi, root)

	// control
	control := fmt.Sprintf("Package: %s\nVersion: %s\nSection: utils\nPriority: optional\nArchitecture: %s\nMaintainer: %s %s - %s\nDescription: Generated by packify\n",
		ifi.FileName,
		ifi.Version,
		ifi.Arch,
		ifi.MaintainerFirstName,
		ifi.MaintainerLastName,
		ifi.MaintainerEmail,
	)
	os.WriteFile(filepath.Join(deb, "control"), []byte(control), 0644)

	copyFile(ifi.BinaryPath, filepath.Join(usrPaths["bin"], ifi.FileName))
	copyFile(ifi.IconPath, filepath.Join(usrPaths["icon"], ifi.FileName+".png"))
	createDesktopIcon(ifi, usrPaths["desktop"], true)

	for _, doc := range ifi.Docs {
		copyFile(doc, filepath.Join(usrPaths["docs"], filepath.Base(doc)))
	}
}

func buildDeb(ifi *InstallationFileInfo, root string) string {
	createDebStructure(ifi, root)
	debFile := fmt.Sprintf("%s_%s_%s.%s", ifi.FileName, ifi.Version, ifi.Arch, ifi.OutputFormat)
	debPath := filepath.Join(filepath.Dir(root), debFile)
	exec.Command("dpkg-deb", "--build", root, debPath).Run()
	return debPath
}

func buildTarGz(ifi *InstallationFileInfo, root string) string {
	var paths []string
	paths = append(paths, ifi.BinaryPath, ifi.IconPath)
	paths = append(paths, ifi.Docs...)

	tarPath := filepath.Join(filepath.Dir(root), fmt.Sprintf("%s_%s_%s.%s", ifi.FileName, ifi.Version, ifi.Arch, ifi.OutputFormat))
	f, _ := os.Create(tarPath)
	defer f.Close()

	gz := gzip.NewWriter(f)
	defer gz.Close()

	tarWriter := tar.NewWriter(gz)
	defer tarWriter.Close()

	for _, path := range paths {
		rel, err := filepath.Rel(path, path)
		if err != nil {
			fmt.Println(err)
		}

		fileInfo, _ := os.Stat(path)
		hdr, err := tar.FileInfoHeader(fileInfo, "")
		if err != nil {
			fmt.Println(err)
		}
		hdr.Name = filepath.ToSlash(rel)

		if err := tarWriter.WriteHeader(hdr); err != nil {
			fmt.Println(err)
		}

		fp, err := os.Open(path)
		if err != nil {
			fmt.Println(err)
		}

		_, err = io.Copy(tarWriter, fp)
		if err != nil {
			fmt.Println(err)
		}
		fp.Close()
	}

	return tarPath
}

func buildAppImage(ifi *InstallationFileInfo, root string) string {
	// Create directories structure
	appDir := filepath.Join(root, "AppDir")
	os.MkdirAll(appDir, 0755)

	// Copy icon file
	copyFile(ifi.IconPath, filepath.Join(appDir, ifi.FileName+".png"))
	createDesktopIcon(ifi, appDir, false)

	usrPaths := createUsrDirs(ifi, appDir)

	// Copy binary, icon, desktop and docs to usr directories
	usrBinaryPath := filepath.Join(usrPaths["bin"], ifi.FileName)
	copyFile(ifi.BinaryPath, usrBinaryPath)
	copyFile(ifi.IconPath, filepath.Join(usrPaths["icon"], ifi.FileName+".png"))
	createDesktopIcon(ifi, usrPaths["desktop"], true)
	for _, doc := range ifi.Docs {
		copyFile(doc, filepath.Join(usrPaths["docs"], filepath.Base(doc)))
	}

	// Create AppRun
	appRun := filepath.Join(appDir, "AppRun")
	appRunSh := fmt.Sprintf("#!/bin/sh\nHERE=\"$(dirname \"$(readlink -f \"$0\")\")\"\nexec \"$HERE/usr/local/bin/%s\" \"$@\"", ifi.FileName)
	os.WriteFile(appRun, []byte(appRunSh), 0755)
	os.Chmod(appRun, 0755)

	tmpTool, err := os.CreateTemp("", "appimagetool")
	if err != nil {
		fmt.Println(err)
	}
	tmpTool.Write(assets.AppImagetoolData)
	tmpTool.Close()
	os.Chmod(tmpTool.Name(), 0755)
	defer os.Remove(tmpTool.Name())

	arch := getArch(runtime.GOARCH)
	outputName := fmt.Sprintf("%s_%s_%s.%s", ifi.FileName, ifi.Version, ifi.Arch, ifi.OutputFormat)
	outputPath := filepath.Join(root, outputName)
	cmd := exec.Command(tmpTool.Name(), appDir, outputPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = append(os.Environ(), "ARCH="+arch)
	if err := cmd.Run(); err != nil {
		fmt.Println(err)
	}
	os.Chmod(outputPath, 0755)
	return outputPath
}

func copyFile(src, dst string) {
	s, _ := os.Open(src)
	d, _ := os.Create(dst)
	defer s.Close()
	defer d.Close()
	io.Copy(d, s)
}

func (ifi *InstallationFileInfo) setInfo(data map[string]any) {
	if v, ok := data["maintainerFirstName"].(string); ok {
		ifi.MaintainerFirstName = v
	}
	if v, ok := data["maintainerLastName"].(string); ok {
		ifi.MaintainerLastName = v
	}
	if v, ok := data["maintainerEmail"].(string); ok {
		ifi.MaintainerEmail = v
	}
	if v, ok := data["fileName"].(string); ok {
		ifi.FileName = v
	}
	if v, ok := data["version"].(string); ok {
		ifi.Version = v
	}
	if v, ok := data["arch"].(string); ok {
		ifi.Arch = v
	}
	if v, ok := data["iconPath"].(string); ok {
		ifi.IconPath = v
	}
	if v, ok := data["binaryPath"].(string); ok {
		ifi.BinaryPath = v
	}
	if v, ok := data["outputFormat"].(string); ok {
		ifi.OutputFormat = v
	}
	if v, ok := data["outputPath"].(string); ok {
		ifi.OutputPath = v
	}
	if v, ok := data["desktopName"].(string); ok {
		ifi.DesktopName = v
	}
	if raw, ok := data["docs"].([]interface{}); ok {
		strs := make([]string, len(raw))
		for i, val := range raw {
			if s, ok := val.(string); ok {
				strs[i] = s
			}
		}
		ifi.Docs = strs
	}
}

func (ifi *InstallationFileInfo) StartProcess(data map[string]any) {
	ifi.setInfo(data)
	rootDir, _ := os.MkdirTemp("", "packify-")
	defer os.RemoveAll(rootDir)

	fmt.Printf("[+] Building %s...", ifi.OutputFormat)

	switch ifi.OutputFormat {
	case "deb":
		debPath := buildDeb(ifi, rootDir)
		copyFile(debPath, filepath.Join(ifi.OutputPath, filepath.Base(debPath)))

	case "tar.gz":
		tarPath := buildTarGz(ifi, rootDir)
		copyFile(tarPath, filepath.Join(ifi.OutputPath, filepath.Base(tarPath)))

	case "AppImage":
		appImagePath := buildAppImage(ifi, rootDir)
		copyFile(appImagePath, filepath.Join(ifi.OutputPath, filepath.Base(appImagePath)))

	default:
		fmt.Println("[-] Unknown format...")
	}
	fmt.Println("✅ Done. Packages saved to:", ifi.OutputPath)
}
