package core

import (
	"archive/tar"
	"compress/gzip"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"packify/config"
	"path/filepath"
	"strings"
)

type Config struct {
	appConfig   *config.AppConfig
	AppName     string
	Version     string
	Arch        string
	IconPath    string
	BinaryPath  string
	OutputDir   string
	DesktopName string
	Docs        []string
}

func NewConfig(appConfig *config.AppConfig) *Config {
	return &Config{appConfig: appConfig}
}

func StartProcess() {
	cfg := getFlags()
	tempDir, _ := os.MkdirTemp("", "debgen")
	defer os.RemoveAll(tempDir)

	fmt.Println("[+] Creating structure...")
	debRoot := filepath.Join(tempDir, cfg.AppName+"-deb")
	createDebStructure(cfg, debRoot)

	fmt.Println("[+] Building .deb...")
	debPath := buildDeb(cfg, debRoot)

	fmt.Println("[+] Building .tar.gz...")
	tarPath := buildTarGz(cfg, debRoot)

	fmt.Println("[+] Building AppImage...")
	appImagePath := buildAppImage(cfg, debRoot)

	os.MkdirAll(cfg.OutputDir, 0755)
	copyFile(debPath, filepath.Join(cfg.OutputDir, filepath.Base(debPath)))
	copyFile(tarPath, filepath.Join(cfg.OutputDir, filepath.Base(tarPath)))
	copyFile(appImagePath, filepath.Join(cfg.OutputDir, filepath.Base(appImagePath)))

	fmt.Println("✅ Done. Packages saved to:", cfg.OutputDir)
}

func getFlags() Config {
	app := flag.String("app", "myapp", "Application name")
	ver := flag.String("version", "1.0.0", "Version")
	arch := flag.String("arch", "amd64", "Architecture (amd64, arm64, i386)")
	icon := flag.String("icon", "icon.png", "Icon file")
	bin := flag.String("bin", "./myapp", "Compiled binary path")
	out := flag.String("out", "./dist", "Output directory")
	docs := flag.String("docs", "README.md,LICENSE", "Comma-separated list of docs")
	flag.Parse()
	return Config{
		AppName:     *app,
		Version:     *ver,
		Arch:        *arch,
		IconPath:    *icon,
		BinaryPath:  *bin,
		OutputDir:   *out,
		DesktopName: *app + ".desktop",
		Docs:        strings.Split(*docs, ","),
	}
}

func createDebStructure(cfg Config, root string) {
	deb := filepath.Join(root, "DEBIAN")
	bin := filepath.Join(root, "usr", "local", "bin")
	icon := filepath.Join(root, "usr", "share", "icons", "hicolor", "256x256", "apps")
	desktop := filepath.Join(root, "usr", "share", "applications")
	doc := filepath.Join(root, "usr", "share", cfg.AppName)
	os.MkdirAll(deb, 0755)
	os.MkdirAll(bin, 0755)
	os.MkdirAll(icon, 0755)
	os.MkdirAll(desktop, 0755)
	os.MkdirAll(doc, 0755)

	// control
	control := fmt.Sprintf(
		`
		Package: %s
		Version: %s
		Section: utils
		Priority: optional
		Architecture: %s
		Maintainer: Ali <ali@example.com>\nDescription: Generated by debgen
		`,
		cfg.AppName, cfg.Version, cfg.Arch,
	)
	os.WriteFile(filepath.Join(deb, "control"), []byte(control), 0644)

	copyFile(cfg.BinaryPath, filepath.Join(bin, cfg.AppName))
	copyFile(cfg.IconPath, filepath.Join(icon, cfg.AppName+".png"))

	desktopEntry := fmt.Sprintf(
		`
		[Desktop Entry]
		Version=1.0
		Name=%s
		Exec=/usr/local/bin/%s
		Icon=%s
		Type=Application
		Categories=Utility;
		`,
		cfg.AppName, cfg.AppName, cfg.AppName,
	)
	os.WriteFile(filepath.Join(desktop, cfg.DesktopName), []byte(desktopEntry), 0644)

	for _, doc := range cfg.Docs {
		copyFile(doc, filepath.Join(root, "usr", "share", cfg.AppName, filepath.Base(doc)))
	}
}

func buildDeb(cfg Config, root string) string {
	debFile := fmt.Sprintf("%s_%s_%s.deb", cfg.AppName, cfg.Version, cfg.Arch)
	debPath := filepath.Join(filepath.Dir(root), debFile)
	exec.Command("dpkg-deb", "--build", root, debPath).Run()
	return debPath
}

func buildTarGz(cfg Config, root string) string {
	tarPath := filepath.Join(filepath.Dir(root), fmt.Sprintf("%s_%s_%s.tar.gz", cfg.AppName, cfg.Version, cfg.Arch))
	f, _ := os.Create(tarPath)
	defer f.Close()

	gz := gzip.NewWriter(f)
	defer gz.Close()

	tarWriter := tar.NewWriter(gz)
	defer tarWriter.Close()

	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}

		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}

		hdr, err := tar.FileInfoHeader(info, "")
		if err != nil {
			return err
		}
		hdr.Name = rel

		if err := tarWriter.WriteHeader(hdr); err != nil {
			return err
		}

		fp, err := os.Open(path)
		if err != nil {
			return err
		}
		defer fp.Close()

		_, err = io.Copy(tarWriter, fp)
		return err
	})

	return tarPath
}

func buildAppImage(cfg Config, root string) string {
	appDir := filepath.Join(filepath.Dir(root), cfg.AppName+".AppDir")
	os.MkdirAll(appDir, 0755)

	exec.Command("cp", "-r", filepath.Join(root, "usr"), appDir).Run()
	appRun := filepath.Join(appDir, "AppRun")
	os.WriteFile(appRun, []byte("#!/bin/sh\nexec /usr/local/bin/"+cfg.AppName), 0755)

	exec.Command("chmod", "+x", appRun).Run()
	appImage := strings.TrimSuffix(appDir, ".AppDir") + ".AppImage"
	exec.Command("appimagetool", appDir, appImage).Run()
	return appImage
}

func copyFile(src, dst string) {
	s, _ := os.Open(src)
	d, _ := os.Create(dst)
	defer s.Close()
	defer d.Close()
	io.Copy(d, s)
}
