#!/bin/sh
set -e

# Desktop entries database refresh
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q
fi

# Icons cache refresh
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f -q /usr/share/icons/hicolor || true
fi

exit 0
